### ISSUE TITLE
Detail sub-pages in a competition page do not render in Firefox

### ISSUE THREAD

**Issue by munael** [codalab/codalab-competitions#3412] opened 2023-08-05 19:56 UTC
If you are having trouble using the site:
-----------------------------------------

1. What browser and version are you using? Firefox x64 116.0 on Windows 11 22H2
2. What is the URL of the problem? Codalab is an open source project, we may not be supporting the instance you are using! https://codalab.lisn.upsaclay.fr/competitions/

## Issue:
- Nothing is rendered in panels/sub-pages that have text/details in them. But the sub-pages for data (which have a table) and for submission (which have a form) seem to be working.
- Screenshot attached.

![image](https://github.com/codalab/codalab-competitions/assets/5769148/cec4e6d6-2f30-492c-8e2c-3fda7572065f)

**Comment by Didayolo** [comment] 2023-08-09 10:55
Hello,

Can you share the URL to the specific competition that is problematic? Or it is all competitions?

I use Firefox and can't reproduce the error.

**Comment by munael** [comment] 2023-08-10 05:18
One example _was_: https://codalab.lisn.upsaclay.fr/competitions/14568#learn_the_details-evaluation

But it's working now somehow. I didn't change or update any apps or add-ons. The errors that were in the console don't show now either.

**Comment by Didayolo** [comment] 2023-08-10 12:50
This is strange indeed. I'll close the issue for now, but feel free to re-open it if you face the issue again.

**Closed by Didayolo** 2023-08-10 12:50 UTC

**Comment by munael** [comment] 2023-08-17 19:46
@Didayolo

Seems the issue is somehow tied to network types? Works on cellular (probably), but not on ADSL?

I'm not behind a VPN or otherwise so...

**Comment by Didayolo** [comment] 2023-08-21 16:22
I don't know either. If you have precise logs or tests that can shed light on the problem, you can share it.
