### ISSUE TITLE
Submissions Tab (Admin) repeated records in table 

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codalab-competitions#3027] opened 2021-11-05 20:48 UTC
In the submissions tab accessible to the admins, when I re-run a submission, two records are shown for it in the table. When I delete one submission then its corresponding two rows are related.

Screenshot:

<img width="802" alt="Screenshot 2021-11-05 at 9 44 07 PM" src="https://user-images.githubusercontent.com/13259262/140576511-9515136d-02a1-49bb-a7b2-e6242f798d7a.png">

Competition link: https://codalab.lisn.upsaclay.fr/my/competition/74

**Comment by Didayolo** [comment] 2021-11-08 23:37
Hi Ihsan,

Thanks for reporting this bug. We'll look into it soon.

**Comment by Didayolo** [comment] 2021-11-09 15:06
I close this issue as I've merged it into #2959.

I think this might be a task for @loicsarrazin as he is already working on #2998 an #2999.

**Comment by loicsarrazin** [comment] 2021-11-11 06:54
Hi @ihsaan-ullah,
What are you using to re-run submissions, the admin submissions view's button? or the user one?  
 I was not able to reproduce locally your problem re-running submissions using this button:  
 
![image](https://user-images.githubusercontent.com/83833966/141251967-931efd0e-71f3-4625-82e6-73becf6fb774.png)

**Comment by ihsaan-ullah** [comment] 2021-11-11 12:57
> Hi @ihsaan-ullah, What are you using to re-run submissions, the admin submissions view's button? or the user one? I was not able to reproduce locally your problem re-running submissions using this button:

Hi @loicsarrazin 
I am re-running the submission using the same button you have highlighted. I have just reproduced the bug on Codalab. You can see in the screenshot, there are 2 rows for each submission.

This screenshot is from this competition: https://codalab.lisn.upsaclay.fr/my/competition/201

<img width="1159" alt="Screenshot 2021-11-11 at 1 56 10 PM" src="https://user-images.githubusercontent.com/13259262/141301744-dcce68e4-444d-4cb6-9128-f25f6893c7fc.png">

**Comment by Didayolo** [comment] 2022-03-23 14:51
I've seen the same issue in the following competition:

https://codalab.lisn.upsaclay.fr/my/competition/1497/

**Comment by Didayolo** [comment] 2022-11-09 16:44
Solved I think.

**Closed** 2022-11-09 16:43 UTC
Labels: Bug, CodalabPy3
