### ISSUE TITLE
stuck in submitting or running

### ISSUE THREAD

**Issue by slnxyr** [codalab/codalab-competitions#3050] opened 2021-12-01 04:59 UTC
Hello, some of the tasks  are stuck in submitting or running status as you can see from the image below. However, I sign up another account and submit the same result, it finished at once.

![BLHK5%2EGQZ`A~T 8143~A0](https://user-images.githubusercontent.com/53633782/144174709-41c8817f-5f6e-4a2d-a132-4d07919641ca.png)

The file in my first task has some error in content, maybe it cause the problem?

What browser and version are you using?
Chrome
What is the URL of the problem?
https://competitions.codalab.org/competitions/36211#participate-submit_results
Username: S13

**Comment by lenyabloko** [comment] 2021-12-01 07:08
I have same problem. Check error log. Mine says:
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.

**Comment by Didayolo** [comment] 2021-12-01 11:12
Hi,

Thanks for reporting.
This is a clone of #3045 so I'll close it. We are actively trying to solve the problem.

> However, I sign up another account and submit the same result, it finished at once.

Other users has reported similar behaviors. Maybe it is just random, it is hard to say.

> The file in my first task has some error in content, maybe it cause the problem?

The problem is general and happens currently on every competitions unfortunately.

> WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.

This warning is unrelated to the issue, it is a common warning on CodaLab even when everything is working well.

**Closed by Didayolo** 2021-12-01 11:12 UTC

**Comment by Josh00-Lu** [comment] 2021-12-03 08:21
> Hello, some of the tasks are stuck in submitting or running status as you can see from the image below. However, I sign up another account and submit the same result, it finished at once.
> 
> ![BLHK5%2EGQZ`AT 8143A0](https://user-images.githubusercontent.com/53633782/144174709-41c8817f-5f6e-4a2d-a132-4d07919641ca.png)
> 
> The file in my first task has some error in content, maybe it cause the problem?
> 
> What browser and version are you using? Chrome What is the URL of the problem? https://competitions.codalab.org/competitions/36211#participate-submit_results Username: S13

classmates uha？
