### ISSUE TITLE
Failed to upload.

### ISSUE THREAD

**Issue by gyy8426** [codalab/codalab-competitions#2512] opened 2019-02-16 11:58 UTC
Hi, I cannot upload my result (about 585MB zipped file) to https://competitions.codalab.org/competitions/19650#participate-get-data. I also try to limit the upload speed, but it doesn't work.

**Comment by KeqiWangSXuniversity** [comment] 2019-02-17 06:16
Have you solved this problem?

**Comment by gyy8426** [comment] 2019-02-19 09:22
> Have you solved this problem?
nope

**Comment by imironhead** [comment] 2019-02-21 02:43
Hi,

I also can not upload a result right now.

I do not know if this information helpful though:

I am in UTC+8 area,

If I upload the results in the morning (~10:00), it almost always fails.

However, it success if I upload them in the evening (~23:00).

Chrome browser showed 3 network requests after clicking the "Submit" button:

1. get_upload_params/  -> status 200
2. prod-private -> status 200
3. prod-private -> status 400 (pending minutes, then get 400)

**Comment by 491506870** [comment] 2019-03-04 03:17
@imironhead hi, i am also in UTC+8, but in the last about 12 hours, i can't submit my results, which i never meet before, each time i choose my file, then i will get nothing later, but the submit botton is pressed all the time, after 5 mins, it tells me that "sorry, failed to upload file", i want to know do you guys have meet this questions? now i am very worried. thank you!

**Comment by joseph-zhang** [comment] 2019-03-04 12:49
@491506870 
get "Sorry, failed to upload file" message box after uploading the whole zip file,
I have been failed to submit my result for a week ...

**Comment by 491506870** [comment] 2019-03-05 07:50
@joseph-zhang hi, i found sometimes i can't submit, but sometime i can... i don't know why, but if you are in UTC+8, maybe you can try to submit in the afternoon, i have submitted successfully many times just now.

**Comment by joseph-zhang** [comment] 2019-03-05 12:14
@491506870 Thx :) 
I tried again 3 hours ago and checked the upload speed.
It seems that "Sorry, failed to upload file" will occur when I encounter a slow upload speed. The upload failed problem may be caused by timeout.

**Comment by LuoweiZhou** [comment] 2019-05-08 15:03
Has anyone figured this out?

**Comment by seddik11** [comment] 2019-07-23 16:33
> Has anyone figured this out?

it is caused by poor upload speed #2654

**Comment by Didayolo** [comment] 2019-09-02 15:19
It seems that there are upload issues when the network connection is slow or unstable.

For those who can upload only during low traffic hours (e.g. 11pm) it can be explained by the fluctuation of your upload speed. It is of course slower when many people use the network (it depends of course on how you access internet).

I close this issue but in the future files uploading could be made more stable.

**Closed by Didayolo** 2019-09-02 15:19 UTC
