### ISSUE TITLE
Default queue congested and failing

### ISSUE THREAD

**Issue by Didayolo** [codalab/codalab-competitions#3413] opened 2023-08-11 10:11 UTC
I observed that the default queue is congested, and several participants are complaining about failing jobs.

With a quick look inside the compute workers, I see a reccurent connection error, shown below.

Also, a competition organizer reported that the size of the submissions uploaded are lower than excepted, which could also be explained by connection problems.

```python
[2023-08-11 09:13:45,158: INFO/Worker-1] Starting new HTTPS connection (1): miniodis-rproxy.lisn.upsaclay.fr
[2023-08-11 09:15:52,458: ERROR/Worker-1] Run task failed (task_id=528953).
Traceback (most recent call last):
  File "/worker/worker.py", line 689, in run
    put_blob(detailed_results_url, file_to_upload)
  File "/worker/worker.py", line 207, in put_blob
    'x-ms-version': '2018-03-28',
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 99, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 335, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 438, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 327, in send
    raise ConnectionError(e)
ConnectionError: HTTPSConnectionPool(host='miniodis-rproxy.lisn.upsaclay.fr', port=443): Max retries exceeded with url: /py3-private/submission_detailed_results/<HIDDEN> (Caused by <class 'socket.error'>: [Errno 110] Connection timed out)
[2023-08-11 09:15:52,461: INFO/Worker-1] Updating task=528953 status to failed
```

**Comment by Didayolo** [comment] 2023-08-11 10:16
@dtuantran Any thoughts on this connection problem?

**Comment by M-leng** [comment] 2023-08-11 12:14
Yes, When I submit to codalab yesterday and today, all submissions are failed or still subimitted.

**Comment by M-leng** [comment] 2023-08-11 12:29
@Didayolo Hello, Didayolo. When will the bug be fixed?

**Comment by dtuantran** [comment] 2023-08-11 12:35
I'm investigating. There are a lot of long running submissions which take > 1h. Maybe it could be another cause.

**Comment by Didayolo** [comment] 2023-08-11 13:32
Same problem on Codabenh workers. This could mean the problem comes from OpenStack.

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/compute_worker.py", line 92, in run_wrapper
    run.start()
  File "/compute_worker.py", line 677, in start
    self._update_status(STATUS_RUNNING, extra_information=f"hostname-{hostname}")
  File "/compute_worker.py", line 324, in _update_status
    self._update_submission(data)
  File "/compute_worker.py", line 302, in _update_submission
    resp = self.requests_session.patch(url, data, timeout=15)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 596, in patch
    return self.request('PATCH', url, data=data, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='www.codabench.org', port=443): Max retries exceeded with url: /api/submissions/16576/ (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f82ea185280>, 'Connection to www.codabench.org timed out. (connect timeout=15)'))
```

**Comment by M-leng** [comment] 2023-08-11 20:39
still failed, but my uploaded is not big.

the error is here:

 `Traceback (most recent call last):
  File "/worker/worker.py", line 708, in run
    put_blob(stdout_url, stdout_file)
  File "/worker/worker.py", line 214, in put_blob
    'x-ms-version': '2018-03-28',
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 99, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 335, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 438, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 327, in send
    raise ConnectionError(e)
ConnectionError: HTTPSConnectionPool(host='miniodis-rproxy.lisn.upsaclay.fr', port=443): Max retries exceeded with url: /py3-private/submission_stdout/1f9dc19d-07a1-4d1e-aa46-c0471c4261e9/stdout.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=EASNOMJFX9QFW4QIY4SL%2F20230811%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230811T202650Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=7d0f91414c015f05f15744b9c5bdceda7f9657ae4f21966bb96e32bf77de6e2f (Caused by : [Errno 110] Connection timed out)`

**Comment by zhuji423** [comment] 2023-08-12 02:06
my submission all failed .
the error message is :
Traceback (most recent call last):
  File "/worker/worker.py", line 347, in run
    raise Exception("Program bundle is not available.")
Exception: Program bundle is not available.

**Comment by zhuji423** [comment] 2023-08-12 04:50
> @Didayolo Hello, Didayolo. When will the bug be fixed?

I want to know it either

**Comment by Didayolo** [comment] 2023-08-12 06:47
We created new compute workers on the default queue, so it should help with the charge and less jobs should be failing.

**Comment by lgeo3** [comment] 2023-08-12 11:30
Tahnks to the new workers on the default queue, I managed to submit a job (which suceeded this morning), but now I still get the same errors as yesterday on new submission: ```    raise ConnectionError(e)
ConnectionError: HTTPSConnectionPool(host='miniodis-rproxy.lisn.upsaclay.fr', port=443): Max retries exceeded with url: /py3-private/submission_output/44761d35-373a-49c9-8f08-10754403dec5/output_file.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=EASNOMJFX9QFW4QIY4SL%2F20230812%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230812T081647Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=27f05b24ef93dbcd547577b09831eae4b0b6f184a013a43ef698ebbfd0174159 (Caused by : [Errno 110] Connection timed out)
```

**Comment by hnuzhy** [comment] 2023-08-13 02:29
Has the submission function been fixed now? It seems that I still cannot submit normally.

**Comment by Didayolo** [comment] 2023-08-14 10:16
@hnuzhy We are still working on it

**Comment by Didayolo** [comment] 2023-08-14 11:31
@lgeo3 @hnuzhy @M-leng 

I don't detect the error anymore. If you face the problem again, please report it.

**Comment by hnuzhy** [comment] 2023-08-14 13:04
> @lgeo3 @hnuzhy @M-leng
> 
> I don't detect the error anymore. If you face the problem again, please report it.

Thank you for your repairing. I'm now being able to submit and evaluate normally.

**Closed** 2023-08-14 15:07 UTC
Labels: Bug, Production server, Workers / Queues

**Comment by zhuji423** [comment] 2023-08-15 01:07
> hello,I still cant submit normally. ![image](https://user-images.githubusercontent.com/52687783/260603435-3a7b1f4a-ee3a-44f9-bdae-1c2322916748.png) But I see the issue is closed, is there any trouble exisit?

the scoring error log is:
 WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
/usr/local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3334: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.8/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
