### ISSUE TITLE
widgets are not working

### ISSUE THREAD

**Issue by DeepDuke** [codalab/codalab-competitions#3474] opened 2024-03-13 03:49 UTC
Hi, it seems the widgets are not working.  I want to paste the `iframe` code to my site to show the leaderboard. But it showed nothing. 
```
<iframe src="http://codalab.lisn.upsaclay.fr/competitions/leaderboard_widget/18028/" style="height: 500px; width: 100%; border: none;"></iframe>
```

**Comment by Didayolo** [comment] 2024-03-13 13:19
Thank you for reporting. Isn't this issue a duplicate of  #3305 ?

**Comment by DeepDuke** [comment] 2024-03-13 14:42
Sorry. It's indeed duplicated.

**Closed as completed** 2024-03-13 14:42 UTC
Labels: Bug

**Comment by Didayolo** [comment] 2024-03-13 15:08
No problem!
