### ISSUE TITLE
Submission Errors 

### ISSUE THREAD

**Issue by kdportillo** [codalab/codalab-competitions#1816] opened 2017-05-26 23:21 UTC
I am trying to run the following example as a trial of Codalab:

[https://github.com/bethard/semeval-codalab](https://github.com/bethard/semeval-codalab)

When I zip the submission folder and upload it, I get the following error: 
`Could not find submission file /codalabtemp/tmpdjvzsg/run/input/res/answer.txt`

I even made the path and placed answer.txt in `input/res` but am still getting the same error. Any suggestions are greatly appreciated. 

**FIXED: My original competition bundle had subdirectories in it that through off the path for finding my files**

**Comment by FlavioAlexander** [comment] 2017-06-22 13:19
Closing because the issue is fixed

**Closed by FlavioAlexander** 2017-06-22 13:19 UTC
