### ISSUE TITLE
Error when uploading

### ISSUE THREAD

**Issue by hackingthegenome** [codalab/codalab-competitions#1593] opened 2016-08-23 05:21 UTC
Hi,

I am new to codalab. I tried starting a new competition using a slightly modified version of the .yaml file from the tutorial.  I got the following errors:

Traceback (most recent call last):
  File "/home/azureuser/codalab/codalab/apps/jobs/models.py", line 231, in run_job_task
    result = computation(job)
  File "/home/azureuser/codalab/codalab/apps/web/tasks.py", line 98, in create_it
    competition = competition_def.unpack()
  File "/home/azureuser/codalab/venv/local/lib/python2.7/site-packages/django/db/transaction.py", line 223, in inner
    return func(_args, *_kwargs)
  File "/home/azureuser/codalab/codalab/apps/web/models.py", line 1404, in unpack
    admins = User.objects.filter(username__in=admin_names.split(','))
AttributeError: 'str' object has no attribute 'objects'

It doesn't look like it's from my code and seems similar to other errors I Found online. However, they were marked as resolved with no explanations, so I wasn't able to get too much out of them.

**Comment by sdpython** [comment] 2016-10-02 10:56
Same issue. I was able to upload once but I'm able to guess what fails on the second time.

**Comment by sdpython** [comment] 2016-10-02 11:00
I solved it by removing the admin parameters from the yaml.

**Comment by codalab** [comment] 2016-11-14 20:38
Duplicate of #1609. Fixed wit commit  6df0be428007b64

**Closed by codalab** 2016-11-14 20:38 UTC
