### ISSUE TITLE
Chahub search engine

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2330] opened 2018-07-08 13:46 UTC
On:

https://www.chahub.org/

- Only the Iris competition shows up in RAMP

- The AutoML competitions do not show up as ChaLearn competitions.

**Comment by ckcollab** [comment] 2018-07-09 19:09
RAMP problems seem caused by the RAMP platform itself? Visiting their page I see:
![image](https://user-images.githubusercontent.com/2185159/42470695-17bf1e14-8370-11e8-98bf-c8f107d0db71.png)

Many main Codalab competitions weren't added yet (like AutoML) because they are pushed to Chahub "upon saving." I saved all existing published competitions, they should all be on there now. I see AutoML properly when searching.

**Comment by ckcollab** [comment] 2018-07-10 18:13
https://www.chahub.org/#?producer=4&q=Causation

Causation challenge not showing up in search:
https://competitions.codalab.org/competitions/1381

**Comment by ckcollab** [comment] 2018-07-10 18:20
> -when I type “causality” all sorts of things show up, but not the causality challenges.

I believe this shows up now properly:

**Comment by ckcollab** [comment] 2018-07-16 15:49
Closing for now, appears fixed

**Closed by ckcollab** 2018-07-16 15:49 UTC
