### ISSUE TITLE
Submit Worksheet to competition

### ISSUE THREAD

**Issue by lr292358** [codalab/codalab-competitions#994] opened 2015-04-29 15:48 UTC
We need means of submitting worksheets to competitions.
There are two ways, the first is easier and the second is better.

1) [P1] Semi-manual way: the result .zip produced by the worksheet that is to be submitted to the competition side encodes the worksheet (e.g. in a separate certificate file); the competition program can check and accept only valid URI.
Certificate file = e.g. hash(hidden_permutation(URI) + hash(zip)), so people cannot use other worksheet with particular results generated.

2) [P2] Fully automatic way (best): Create a feature: submit the worksheet results to a competition from command line. Link worksheets on competition results and public submission boards.

**Comment by ErickWa** [comment] 2016-07-06 20:35
Closing as duplicate of #1559

**Closed by ErickWa** 2016-07-06 20:35 UTC
Labels: Competition, Enhancement, Feature, Ice Box, Worksheets
