### ISSUE TITLE
Email support for forums

### ISSUE THREAD

**Issue by AishwaryaAgrawal** [codalab/codalab-competitions#1529] opened 2016-02-25 21:11 UTC
How can I link an email account to the forums in challenges? I want that whenever someone posts in the forum, I get an email notification about it.

**Comment by FlavioAlexander** [comment] 2016-11-11 21:36
@AishwaryaAgrawal We don't have this feature in place. However, I will keep it around, seems like a nice thing to have, specially for `admins` and `organizers`.

**Comment by FlavioAlexander** [comment] 2016-11-14 21:19
Duplicate of #1566.

**Closed by FlavioAlexander** 2016-11-14 21:19 UTC
Labels: Competition, Enhancement, Feature, P4
