### ISSUE TITLE
not in a team after creating a team

### ISSUE THREAD

**Issue by youkaichao** [codalab/codalab-competitions#2336] opened 2018-07-15 07:45 UTC
after I create a team, it still says "You are not in any team for this competition. You can create a new team or request enrollment to an existing team". That said, I can't manage the team nor allow requests from others.

broser : chrome 67.0.3396.99
url: https://competitions.codalab.org/competitions/19113

**Comment by Tthomas63** [comment] 2018-07-16 18:32
Hello @youkaichao,

This seems to be caused by a bug that was recently introduced into the code. We'll take a look and hopefully let you know more shortly. 

Thanks,
Tyler

**Comment by willprice** [comment] 2018-07-25 10:58
Hi @Tthomas63,
We're also experiencing this issue. Thanks for looking into the issue :)

**Comment by Tthomas63** [comment] 2018-08-06 20:04
Hello All,

This bug seems to be caused by a set of features we implemented around April 30th. These features are un-used so we will potentially be rolling back these changes.

If you are using OrganizerTeams instead of regular teams please let us know as this will depreciate them.

Thanks for your patience, and best regards,
Tyler

**Comment by willprice** [comment] 2018-08-07 18:50
Hi @Tthomas63,

Thanks for looking into this. I've got OrganizerTeams enabled for a competition, but I don't actually know what it enables, I could never find a clear description of its purpose.

**Comment by Tthomas63** [comment] 2018-08-09 18:51
Hello @willprice,

OrganizerTeams was a feature to allow the competition organizers to manage the teams instead of users. This could be carried out from the `participants` page where you had the option of filling out a form or uploading a CSV to create teams.

![image](https://user-images.githubusercontent.com/28552312/43919271-476a5bc0-9bca-11e8-9a0b-44ec46fca967.png)

Best regards,
Tyler

**Comment by willprice** [comment] 2018-08-10 08:41
Hi @Tthomas63,

Thanks for the clear explanation of the feature. I don't think that is something our competition will need to make use of over participant defined teams providing we can moderate the teams created.

Many thanks,

**Comment by Tthomas63** [comment] 2018-08-17 19:28
Hello all,

Sorry for the wait. This issue should be fixed and we have added a test to help us figure out when this breaks again.

Please let us know if you still encounter any issues!

Best regards,
Tyler

**Closed by Tthomas63** 2018-08-17 19:28 UTC

**Comment by willprice** [comment] 2018-08-19 22:10
Super, thanks Tyler. I'll let you know if we encounter any further issues with teams.
