### ISSUE TITLE
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. 

### ISSUE THREAD

**Issue by Harvey5678** [codalab/codalab-competitions#3140] opened 2022-04-01 06:56 UTC
Hi:

I created my own challenge and wanted to use my own docker. However, this is the error I got after one submission:

WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "python": executable file not found in $PATH: unknown.

What could be the problem?
This is the link to my challenge:
https://codalab.lisn.upsaclay.fr/competitions/3087?secret_key=f88541e1-876e-4e74-b898-5accb44fabc7

I've made pavao and tthomas63 the admins. It will be awesome if you can access my competition and help me to debug.

What's more, I think the path is not correct. In my docker, on /build directory I use

python3 -m service.LocalEvaluation --ref-data PATH/TO/REFERENCE --user-data PATH/TO/USER_INPUT --out ./report.json

to run my evaluation code. How could I set up the metadata file to let codaLab execute my evaluation program inside my own docker?

Thank you for your help

**Comment by Didayolo** [comment] 2022-05-10 16:21
Hello,

I thought I have already comment this issue, but apparently not, sorry.

Do you still have this problem?

It is a bit hard to tell what the problem is just like this. You should try to begin with a working example and modify the code step by step and test it locally.
The command used can be defined in the `metadata` file of the scoring (or ingestion) program.

**Comment by Didayolo** [comment] 2022-06-21 15:10
I close this issue because of the lack of reply. Feel free to re-open with more information if you need help.

**Closed by Didayolo** 2022-06-21 15:10 UTC
