### ISSUE TITLE
LRI server: bug in saving edits

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2878] opened 2020-12-11 00:43 UTC
Competition:
https://codalab.lri.fr/competitions/783

When changes are made with the editor, they take effect, but we get the following message when we save changes:

<img width="724" alt="Screen Shot 2020-12-10 at 4 40 18 PM" src="https://user-images.githubusercontent.com/7594063/101846846-ad674180-3b06-11eb-9456-94fe6af2b7a5.png">

**Comment by madclam** [comment] 2020-12-11 03:09
Sometimes the changes are saved ans sometimes not.

**Comment by madclam** [comment] 2020-12-11 03:10
This is the same bug as https://github.com/codalab/codalab-competitions/issues/2874

**Comment by Didayolo** [comment] 2020-12-15 16:57
The issue is solved now.

TODO:

- Merge the working code into the right Github branch
- Documentation about migrating from Python2 to Python3?

**Comment by Didayolo** [comment] 2021-05-21 14:24
Merged.

**Closed by Didayolo** 2021-05-21 14:24 UTC
Labels: Bug, CodalabPy3

**Comment by Didayolo** [comment] 2021-09-21 13:50
This issue still happens in [codalab.lisn.fr](codalab.lisn.fr)

**Comment by Didayolo** [comment] 2021-09-28 14:28
Remark: the changes are taken into account even if there is an error message

**Comment by Didayolo** [comment] 2021-09-29 14:16
This issue is resolved!
