### ISSUE TITLE
submission error!

### ISSUE THREAD

**Issue by lancexiang** [codalab/codalab-competitions#2485] opened 2019-01-02 03:37 UTC
I have failed five times for this error message:
```python
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/tmp/codalab/tmp2acs6o/run/program/evaluate.py", line 67, in 
    "Missing volume: {}".format(submission_volume_path))
ValueError: Submission volume not found - terminating!
Missing volume: /tmp/codalab/tmp2acs6o/run/input/res/test-segmentation-0.nii
```
But I see the submission keep going, so why do this?

![](https://ws2.sinaimg.cn/large/006tNbRwly1fys33rzoz1j31a40lote7.jpg)

**Comment by ckcollab** [comment] 2019-01-02 05:16
duplicate of #2334 #2480

Were you able to get ahold of the competition organizer? Please don't post duplicate issues, closing this one as ***this competition is ran by someone outside of Codalab, please contact them.***

**Closed by ckcollab** 2019-01-02 05:16 UTC

**Comment by mingxiu1** [comment] 2019-08-16 12:16
> I have failed five times for this error message:
> 
> ```python
> WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
> Traceback (most recent call last):
>   File "/tmp/codalab/tmp2acs6o/run/program/evaluate.py", line 67, in 
>     "Missing volume: {}".format(submission_volume_path))
> ValueError: Submission volume not found - terminating!
> Missing volume: /tmp/codalab/tmp2acs6o/run/input/res/test-segmentation-0.nii
> ```
> 
> But I see the submission keep going, so why do this?
> 
> ![](https://camo.githubusercontent.com/e08f0f06a6c2646af9c354d2c81f931eabf882ec/68747470733a2f2f7773322e73696e61696d672e636e2f6c617267652f303036744e6252776c79316679733333727a6f7a316a33316134306c6f7465372e6a7067)

Hello, I want to ask, have you solved your problem?Because I had the same problem, and I didn't know what to do

**Comment by ckcollab** [comment] 2019-08-16 16:43
The warning about swap is just a warning, and it looks like you have an error in the structure of your submission? Please contact your competition's organizer
