### ISSUE TITLE
[CodalabPy3] Impossible to make submissions after a deadline extension

### ISSUE THREAD

**Issue by BDonnot** [codalab/codalab-competitions#2856] opened 2020-10-31 14:46 UTC
Hello,

I wanted to test whether it would be possible to extend the deadline of a competition in the new version of codalab (based on python3).

And apparently it is not possible.

I try to extend a deadline (using the admin panel) but when i wanted to submit i got this error message:
> "Failed, competition phase is being migrated, please try again in a few minutes"

It's been 3 or 4 days, and it's still not possible to post any new submission on the competition.
So i guess this feature is not really working.

Benjamin

**Comment by Didayolo** [comment] 2020-11-01 17:24
That's a specific test, well done!

**Comment by Didayolo** [comment] 2021-05-21 14:25
Merged.

**Closed by Didayolo** 2021-05-21 14:25 UTC
Labels: CodalabPy3, P2

**Comment by Didayolo** [comment] 2021-09-29 14:50
This is working now. Either the problem has been solved, or the error message was caused by something else.
