### ISSUE TITLE
Error trying to make a submission public

### ISSUE THREAD

**Issue by vponcelo** [codalab/codalab-competitions#1569] opened 2016-07-13 20:31 UTC
Hi,

I need to make the submissions public on the following coopetition:

https://competitions.codalab.org/competitions/10751

When I try to do it from a given submissions within the submissions panel, the following error appears:

![image](https://cloud.githubusercontent.com/assets/3542257/16818623/03345314-4949-11e6-809d-36d03b7c242a.png)

But my internet connection is working fine. 

In this modality of competition, having public submissions among all participants is required in order to allow collaboration between them.

Looking forward for your answer.

Thank you very much in advance.

**Comment by FlavioAlexander** [comment] 2016-07-13 22:14
@vponcelo The feature should be working fine, I just tried in one of my competitions. Could you try again please? Let me know if you get the same error

**Comment by vponcelo** [comment] 2016-07-14 10:27
@FlavioAlexander thank you again. In the competition I linked before, it does work but only for my own submissions. I presume it only works if the participants who make the submissions activate this feature themselves. Because if I try to make a submission of other person public, then it shows the error above. I guess I should also be able to do that as an organizer. Otherwise, should we ask for participants to do that when they perform their submissions?

**Comment by FlavioAlexander** [comment] 2016-07-14 20:11
@vponcelo You are correct, you need to own the submission to make it public.  At this moment, you won't be able to make other participants' submissions public. You need to ask them to make their submissions public after the submission is done. I should probably think of a better error message since it does not reflect what the problem is

**Comment by FlavioAlexander** [comment] 2016-07-14 20:27
@vponcelo Since I have answered your question I will close this issue, but I opened a new issue to follow up with allowing organizers to public submissions https://github.com/codalab/codalab-competitions/issues/1570

**Closed by FlavioAlexander** 2016-07-14 20:27 UTC

**Comment by vponcelo** [comment] 2016-07-14 21:22
Thank you @FlavioAlexander.
