### ISSUE TITLE
Strange random OSError

### ISSUE THREAD

**Issue by tahasaf** [codalab/codalab-competitions#2866] opened 2020-11-15 17:29 UTC
Dear Codalab developpers,

We have a strange problem these last days. Submissions took a long time before running, It works sometimes (randomly) but it often fail with the following message:

Traceback (most recent call last):
  File "/worker/worker.py", line 600, in run
    evaluator_process.kill()
  File "/usr/local/lib/python2.7/subprocess.py", line 1279, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/local/lib/python2.7/subprocess.py", line 1269, in send_signal
    os.kill(self.pid, sig)
OSError: [Errno 3] No such process

The error seems to occur before running the submitted code.

We use ingestion to run the code and compute the score.

thank you for help

**Comment by Didayolo** [comment] 2020-11-17 16:20
Hi,

Thank you for reporting this issue. Can you provide more information so we can reproduce the error?

**Comment by Didayolo** [comment] 2021-01-06 16:51
I close the issue because it's staling, feel free to re-open it if needed.

**Closed** 2021-01-06 16:51 UTC
