### ISSUE TITLE
Add support@codalab.org email

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#1224] opened 2015-08-14 18:29 UTC
@ErickWa assigned this to you, let me know how to proceed on this one!

**Comment by FlavioAlexander** [comment] 2015-10-09 21:51
@ErickWa @ckcollab Are we still discussing about this, or should I close it?

**Comment by ErickWa** [comment] 2015-10-09 21:54
Don't close it - we need to add some A-Records to the DNS, set up email, etc.

The problem is that this DNS is registered under a former employee of the Outercurve Foundation, and he is no longer available.

I have a call in to the Engineering Director at MSR to get this fixed.

Best, -- Erick

**Comment by FlavioAlexander** [comment] 2015-10-09 22:13
@ErickWa Just checking, not a problem.

Best,

Flavio

**Closed** 2017-09-22 07:06 UTC
Labels: Question/Discussion, Stabilization
