### ISSUE TITLE
Submission error

### ISSUE THREAD

**Issue by JinfengZ** [codalab/codalab-competitions#3414] opened 2023-08-12 01:41 UTC
I tried several times to submit predictions and only successful once. Here is the error message:
Traceback (most recent call last):
  File "/worker/worker.py", line 729, in run
    put_blob(output_url, output_file)
  File "/worker/worker.py", line 214, in put_blob
    'x-ms-version': '2018-03-28',
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 99, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 335, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 438, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 327, in send
    raise ConnectionError(e)
ConnectionError: HTTPSConnectionPool(host='miniodis-rproxy.lisn.upsaclay.fr', port=443): Max retries exceeded with url: /py3-private/submission_prediction_output/eaea3dd8-7295-4d75-911b-17e56da17eef/output.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=EASNOMJFX9QFW4QIY4SL%2F20230811%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230811T232250Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=d462eec984e947f8678d5e40e7233d5b210e2b0487eb7f6ed81d1dab93bcfca8 (Caused by : [Errno 110] Connection timed out)

**Comment by Didayolo** [comment] 2023-08-12 06:48
Thank you for reporting. I close this issue as it is a duplicate of #3413.

**Closed by Didayolo** 2023-08-12 06:48 UTC
