### ISSUE TITLE
Safari weird layout

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2428] opened 2018-10-06 00:00 UTC
This concerns the Google staging server for AutoDL, competition 40.
Using Safari, the menu ins UNDER the separation bar of the header, instead of below. Chrome, Explorer, and Firefox OK.

<img width="1384" alt="screen shot 2018-10-05 at 4 57 31 pm" src="https://user-images.githubusercontent.com/7594063/46565010-2c75e500-c8c0-11e8-9829-6db5f8e2c757.png">
<img width="1162" alt="screen shot 2018-10-05 at 4 57 45 pm" src="https://user-images.githubusercontent.com/7594063/46565011-2c75e500-c8c0-11e8-917c-99521129a70c.png">

**Comment by Tthomas63** [comment] 2018-10-08 22:02
I found the issue with this and have pushed a fix to the staging server. It slightly alters the styling of the tabs but it should fix the issues with the Safari display:

Chrome:
![image](https://user-images.githubusercontent.com/28552312/46635792-74884800-cb0a-11e8-8478-337a22560115.png)

Safari:
![image](https://user-images.githubusercontent.com/28552312/46635836-984b8e00-cb0a-11e8-8748-8a4fadde9ada.png)

**Comment by madclam** [comment] 2018-10-09 22:00
Using Safari I cannot upload files: There was an error uploading the file. Please try again.

**Comment by Tthomas63** [comment] 2018-10-11 04:54
I think this may have been caused by something else like a momentary drop in connection or slow upload speed. When testing today between Zhengying, Ted and myself we were able to successfully make submissions from Safari.

**Closed** 2018-10-16 18:02 UTC
Labels: Bug, P1
