### ISSUE TITLE
Submissions by CIKM competition participants are stuck at Submitted, and are not getting executed

### ISSUE THREAD

**Issue by hadylauw** [codalab/codalab-competitions#1878] opened 2017-07-27 04:28 UTC
Hi CodaLab,

We are currently running a CIKM AnalytiCup 2017 data science competition on CodaLab right now: https://competitions.codalab.org/competitions/16652.

Recently, our participants have been experiencing difficulties in getting their submissions scored.  All their submissions for the past 20 hours are stuck at "Submitted", and are not getting executed by the CodaLab servers.

Since we are at the final few days of the competition (that will end by 31 July), we urgently need to get our participants to be able to get their final submissions scored.

Could you please take a look at it soon, and help us resolve it?  We really appreciate your help with this.

Thank you.

Hady (CIKM AnalytiCup 2017 Co-Chair)

**Comment by iamkaram** [comment] 2017-07-27 08:02
Submission got stuck with the submitted status.. It is not going through for last 24 hours.

**Comment by ckcollab** [comment] 2017-07-28 06:05
Apologies for these problems, we should have new servers up soon to deal with the increased usage.

Closing this as it seems to be a duplicate of #1873

**Closed by ckcollab** 2017-07-28 06:05 UTC

**Comment by tienthanhdhcn** [comment] 2017-07-28 07:40
@ckcollab Thank you for your help, please can you give us a specific time for the new servers up (i.e., how soon is that)? The problem has been still there for more than 2 days and the deadline is approaching.
