### ISSUE TITLE
Submission status stuck in 'running' for a long time

### ISSUE THREAD

**Issue by walter198** [codalab/codalab-competitions#3045] opened 2021-11-28 11:47 UTC
Hi, I have submitted the results, but it is stuck in 'running' for a long time, say more than 2 days. Normally it only takes 2~ 3 hours, could you please help check it? Thank you very much!

1. What browser and version are you using?
   Google chrome.
2. What is the URL of the problem? Codalab is an open source project, we may not be supporting the instance you are using!
   The URL of my submission page: https://competitions.codalab.org/competitions/17094#participate-submit_results

**Comment by CacacaLalala** [comment] 2021-11-29 02:19
Same issue.

**Comment by leahyyy** [comment] 2021-11-29 07:20
Same issue.

**Comment by biansy000** [comment] 2021-11-29 11:54
I meet similar problems. But the difference is that, after I submit the results, it is stuck in "submitting" for over 2 days, not the "running" state as mentioned above.

**Comment by Didayolo** [comment] 2021-11-29 13:08
Hi,

I think the queue is over used. The activity is currently very high on the platform (maybe because of the upcoming NeurIPS conference?), and some of the compute workers has been moved to the [new server](https://codalab.lisn.fr/). We'll see if we can do anything to help with this situation.

**Comment by KaiHe-better** [comment] 2021-11-29 13:47
> Hi,
> 
> I think the queue is over used. The activity is currently very high on the platform (maybe because of the upcoming NeurIPS conference?), and some of the compute workers has been moved to the [new server](https://codalab.lisn.fr/). We'll see if we can do anything to help with this situation.

so，what can we do to get results from old  platform ? I am wondering is the waiting for more time work ?

**Comment by Didayolo** [comment] 2021-11-29 16:40
> so，what can we do to get results from old platform ? I am wondering is the waiting for more time work ?

I can see that submissions are running on the main queue, so yes, waiting should work.
We will try to add some more workers if possible. In any case, sorry for the inconvenience.

I'd like to remind competition organizers that you can provide your own computational resources (see [Using your own compute workers](https://github.com/codalab/codalab-competitions/wiki/User_Using-your-own-compute-workers)) in order to avoid problems linked to the free job queue. This way the jobs of your competition can be independent and quicker.

**Comment by luisespinosaanke** [comment] 2021-11-29 21:27
Hi all,

Thanks for the great platform! Same here, I'm a co-organizer of this [SemEval competition](https://competitions.codalab.org/competitions/34344) and  we are having trouble posting one of the baseline results (submission gets stuck on Running). In the Submissions tab we can also see a few submissions from participants stuck on _submitting_ or _running_. 

Should we ask these participants to try again in a few days, and remove these stuck submissions by hand, would this help?

Thanks!

**Comment by Didayolo** [comment] 2021-11-30 11:55
> stuck on submitting or running.

If it's stuck on running then it may be cluttering the queue!

> Should we ask these participants to try again in a few days, and remove these stuck submissions by hand, would this help?

I don't know if this would help. It is possible that removing submissions from the admin panel does not really remove them from the compute queue. The best advice is to avoid re-uploading to avoid slowing down the queue even more.

**Comment by yoxu515** [comment] 2021-11-30 11:58
same issue

**Comment by Didayolo** [comment] 2021-11-30 11:58
I think I've spot the issue!

When submission fail, they get stuck for more than 2 hours. I'll dig into it.

**Comment by slnxyr** [comment] 2021-11-30 13:56
similar issue 
It is stuck in "submitting" .But when I change an account and submit the same result, it finished immediately.

**Comment by Didayolo** [comment] 2021-11-30 18:42
> similar issue, It is stuck in "submitting" .But when I change an account and submit the same result, it finished immediately.

It seems to be quite irregular. Please try to avoid any useful submissions while we try to fix the problem.

**Comment by lenyabloko** [comment] 2021-12-01 07:05
I have the same issue. Error log says:
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.

**Comment by asimadnan** [comment] 2021-12-01 08:44
Hi,
Any ETA for when this would be fixed?
I have to get some results for a paper submission thats due next week.

**Comment by Didayolo** [comment] 2021-12-01 11:17
> WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.

This warning is unrelated to the issue, it is a common warning on CodaLab even when everything is working well.

> Any ETA for when this would be fixed?

It is hard to say as the problem is not clearly identified (apart from the fact that the old server is less resistant against big charge/activity as experiencing right now). In the best case it would be solved today but it could last for days.
If you are a challenge organizer, you can re-upload your bundle on the [new server](https://codalab.lisn.fr) in order to compute your submissions and get results for your paper.

**Comment by Didayolo** [comment] 2021-12-01 16:07
The problem seems to be solved now. 

Already boggus submissions won't work, but you can re-submit them.

**Comment by Didayolo** [comment] 2021-12-02 00:27
I close this issue now. Feel free to re-open it if you still face the issue.

**Closed by Didayolo** 2021-12-02 00:27 UTC
Labels: Worker/Queues

**Comment by mrqorib** [comment] 2021-12-03 13:21
Hi, my submissions are still stuck in submitting for the [BEA-2019 shared task](https://competitions.codalab.org/competitions/20228). Thanks.

**Comment by H-TayyarMadabushi** [comment] 2021-12-03 14:21
Hi, 

We are having the same problem for for [SemEval 2022 Task 2](https://competitions.codalab.org/competitions/34710): All submissions after Dec. 2, 2021, 2:44 p.m. are stuck in the "Submitting" status.
