### ISSUE TITLE
Trouble when submitting in the platform

### ISSUE THREAD

**Issue by truongchau2602** [codalab/codalab-competitions#3410] opened 2023-07-31 12:17 UTC
![image](https://github.com/codalab/codalab-competitions/assets/64648373/c7c5e909-5ffe-4b2a-b939-8d810f3d6fcb)

"Failed, competition phase is being migrated, please try again in a few minutes"
This error is always showing up whenever I submit the zip file in "2023 IEEE SPS Video and Image Processing Cup (VIP Cup) Ophthalmic Biomarker Detection" competition. Is this a problem from my account?

**Comment by dtuantran** [comment] 2023-07-31 14:20
Dear @truongchau2602 ,

I can upload submission zip normally. We can't reproduce your issue. It seems related to competition configurations. Are you still having this issue ?

**Comment by truongchau2602** [comment] 2023-08-02 05:08
Yes. The issue sometimes persists even when I switch to a different account to submit the .zip result file.

**Comment by Didayolo** [comment] 2023-08-09 10:28
- Are you participant or organizer of the competition?
- Are you submitting to the right phase?
- Is the base submission provided by the organizers working?
- Did you change something inside the submission and made the ZIP manually?
- Can you share your ZIP and the URL to the competition?

**Comment by Didayolo** [comment] 2023-08-28 14:15
Merged with #3426.

**Closed by Didayolo** 2023-08-28 14:15 UTC
