### ISSUE TITLE
Add phase feature in the Competition Editor

### ISSUE THREAD

**Issue by loicsarrazin** [codalab/codalab-competitions#2971] opened 2021-07-20 20:41 UTC
on branches develop and lri-py3-storage, there is a button in the Competition editor (edit.html) that allows the competition admin to add a phase to its competition.  The button was removed from the production versions.

The feature is implemented but not fully operational. 

After adding a phase to a competition in the editor, the phase form is generated, and its file fields (Input Data, Reference Data, etc.) possible values are unrestricted, allowing the user to select any bundle uploaded by any user. The file fields of already existing phases do not have this problem. 

It is needed to reactivate the button and fix the possible selections of file fields of a newly added phase.

**Comment by Didayolo** [comment] 2021-10-13 09:35
Just to clarify: are there branches where this feature works?

**Comment by Didayolo** [comment] 2021-12-02 15:49
I close the issue here because it is merged in #2686. The issue is still to be solved.

**Closed by Didayolo** 2021-12-02 15:49 UTC
Labels: Enhancement
