### ISSUE TITLE
The main competition portal is inaccessible...

### ISSUE THREAD

**Issue by zhimin-z** [codalab/codalab-competitions#3523] opened 2024-09-21 21:47 UTC
Check https://competitions.codalab.org/competitions but found:
<img width="674" alt="image" src="https://github.com/user-attachments/assets/e75ad93e-487f-49de-b753-ea99f441c150">

**Comment by Didayolo** [comment] 2024-09-26 14:30
Are you still experiencing the problem? Personnaly I can access it.

By the way, this is an archive server, the current production servers are:
- https://codalab.lisn.upsaclay.fr/
- https://www.codabench.org/

**Comment by zhimin-z** [comment] 2024-09-26 14:40
> Are you still experiencing the problem? Personnaly I can access it.
> 
> By the way, this is an archive server, the current production servers are:
> 
> * https://codalab.lisn.upsaclay.fr/
> * https://www.codabench.org/

No, the archived website is still inaccessible for me...

**Comment by Didayolo** [comment] 2024-10-01 15:28
Maybe try a different browser? Or a different network?

**Comment by zhimin-z** [comment] 2024-10-01 15:30
> Maybe try a different browser? Or a different network?

Still does not work for me...

**Comment by Didayolo** [comment] 2024-10-22 21:16
I'm closing this issue as nobody can reproduce it.

**Closed as completed by Didayolo** 2024-10-22 21:16 UTC

**Comment by zhimin-z** [comment] 2024-10-22 21:18
> I'm closing this issue as nobody can reproduce it.

Tried with different browsers and different network providers, but still failed to access to the website :(

**Comment by Didayolo** [comment] 2024-10-23 08:07
@zhimin-z I am sorry for you... Try to contact your internet provider or network administrator if relevant.

**Comment by zhimin-z** [comment] 2024-10-23 12:33
> @zhimin-z I am sorry for you... Try to contact your internet provider or network administrator if relevant.

Would you mind telling me your location? I tested in Canada and my friend also tested it in China and both of us could not access to this website.

**Comment by Didayolo** [comment] 2024-10-23 13:06
I am located in France. The project should be accessible wordwild. @ObadaS any thought on this?

**Comment by ObadaS** [comment] 2024-10-23 13:28
Hello, the website is currently down because our provider is having some technical difficulties.
Both https://competitions.codalab.org/competitions and https://autodl.lri.fr are down for the moment.

However, https://codabench.org and https://codalab.lisn.upsaclay.fr/ (the current active platform) are fine.

**Comment by zhimin-z** [comment] 2024-10-23 13:40
> Hello, the website is currently down because our provider is having some technical difficulties. Both https://competitions.codalab.org/competitions and https://autodl.lri.fr are down for the moment.
> 
> However, https://codabench.org and https://codalab.lisn.upsaclay.fr/ (the current active platform) are fine.

Thanks, that is indeed an issue for us. No wonder I cannot access to it :X

**Comment by ObadaS** [comment] 2024-10-23 15:00
@zhimin-z The issue has been fixed. Feel free to reopen the issue or create a new one if you still have problems connecting to any of the instances

**Comment by zhimin-z** [comment] 2024-10-23 15:53
> @zhimin-z The issue has been fixed. Feel free to reopen the issue or create a new one if you still have problems connecting to any of the instances

Fine, but it still does not work from my side:
<img width="1463" alt="image" src="https://github.com/user-attachments/assets/6ac7661a-cf29-40de-8eae-39b8746f8533">

**Comment by ObadaS** [comment] 2024-10-23 16:03
Weird, I just loaded it and it still works on my end. 

Can you try opening the link in a private tab/browser ?
If that doesn't work, can you try using a VPN ?

I would also like the results of the `curl -v https://competitions.codalab.org/competitions` command if possible and the `traceroute competitions.codalab.org` command, it might shed some more light on where the issue might be

**Comment by zhimin-z** [comment] 2024-10-24 12:57
> Weird, I just loaded it and it still works on my end.
> 
> Can you try opening the link in a private tab/browser ? If that doesn't work, can you try using a VPN ?
> 
> I would also like the results of the `curl -v https://competitions.codalab.org/competitions` command if possible and the `traceroute competitions.codalab.org` command, it might shed some more light on where the issue might be

Sure, I have tried with incognito mode, and I successfully logged in.
Then I tried with usual mode, but it still fails to access.
I think this might be attributed to the cookie, thus I clear all cookies and refresh, and this time I successfully log in.

@ObadaS Thanks, it worked eventually!
