### ISSUE TITLE
issue in submission of tsv file in competition

### ISSUE THREAD

**Issue by M-SRIKAR-VARDHAN** [codalab/codalab-competitions#3526] opened 2024-10-05 11:17 UTC
What browser and version are you using? [ Chrome Version 95.0.4638.69]
What is the URL of the problem? [Codalab URL, e.g., https://codalab.lisn.upsaclay.fr/competitions/20118/]

**Comment by Didayolo** [comment] 2024-10-11 13:19
Hi @M-SRIKAR-VARDHAN,

Please share more details about your problem:
- Are you organizer or participant of the challenge?
- What is the URL of the competition?
- What is your username?
- Was it working before?
- What are the symptoms?

**Comment by M-SRIKAR-VARDHAN** [comment] 2024-10-12 13:45
> Hi @M-SRIKAR-VARDHAN,
> 
> Please share more details about your problem:
> 
> * Are you organizer or participant of the challenge?
> * What is the URL of the competition?
> * What is your username?
> * Was it working before?
> * What are the symptoms?

participants
https://codalab.lisn.upsaclay.fr/competitions/20118#participate-submit_results
nits_teja_srikar
no
cant submit in chrome but can submit from other search engines

**Comment by Didayolo** [comment] 2024-10-14 10:11
Thank you for reporting the bug. I close the issue because it is a duplicate of #3503.

**Closed as completed by Didayolo** 2024-10-14 10:11 UTC
Labels: competition-specific
