### ISSUE TITLE
Competition dump failed

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2105] opened 2017-12-03 00:01 UTC
I could not dump https://codalab.lri.fr/competitions/111

**Comment by Tthomas63** [comment] 2017-12-08 22:13
Hello Isabelle,

The error seems to be unique to this competition. While I'm unsure of the cause, it seems to be a communication problem with Azure. I will look into this and should have more info soon.

Thanks, Tyler

**Comment by Tthomas63** [comment] 2017-12-14 20:38
Closing this issue for now, as we were un-able to track-down the issue. This seems to have been caused by a user error relating to the competition, as the error is specific to this competition and it's files.

**Comment by madclam** [comment] 2018-01-27 11:24
I still cannot dump this competition.
What kind of error is this? Even dump without datasets does not work.
![image](https://user-images.githubusercontent.com/7594063/35471508-e250f31c-035c-11e8-82d1-92af9e756fee.png)

**Comment by Tthomas63** [comment] 2018-01-29 20:38
Hello Isabelle,

The error states that we are missing an Azure Content Type Header when communicating with Azure. This has only ever happened with this competition, and it does not seem to matter whether we use URI keys or actual files. We've looked into the issue and it is not exactly clear why this is only happening with this competition. Perhaps one of the files uploaded with the competition is corrupt, or has some other issue.

Best regards,

**Closed** 2018-02-21 19:28 UTC
Labels: Bug, Chore, P3
