### ISSUE TITLE
Inconsistency in leaderboard's computed field

### ISSUE THREAD

**Issue by ndido98** [codalab/codalab-competitions#3496] opened 2024-05-30 09:25 UTC
I am running this challenge: [https://codalab.lisn.upsaclay.fr/competitions/18998](https://codalab.lisn.upsaclay.fr/competitions/18998)

As you can see in the results page, we have four leaderboards (one per sub-track). In each sub-track there is a "Mean score" column, defined in the uploaded YAML file as a computed Avg column of trackXYdisk1-5 (where XY is 11, 12, 21 or 22).
In particular, we noticed that the mean is inconsistent with the other five values.
We then noticed that all example competition YAML files define this column's label as "< Rank >", and we probably thought it is some kind of undocumented magic label that changes the behavior of how the column is handled. We then proceeded to rename the columns with the Edit page of the competition, but not only the leaderboards have still the column named "Mean score", but the result is still wrong. What can we do to fix it? Our goal is to rank submissions in each sub-track by their mean score column.

**Comment by Didayolo** [comment] 2024-05-30 10:02
Unfortunately, editing the leaderboard columns once the competition is created is something that is not working as intended. Sorry for the inconvenience.

See #2686.

I replied to your email asking for more information about your YAML file. I close this issue to continue the discussion by email.

**Closed as completed by Didayolo** 2024-05-30 10:02 UTC
