### ISSUE TITLE
Participants Unable to Submit Test Results Correctly

### ISSUE THREAD

**Issue by ZhuoYulang** [codalab/codalab-competitions#3535] opened 2024-10-21 14:36 UTC
***This is a template, please remove any non-relevant details to your issue***

If you are an organizer and have problem hosting your competition:
------------------------------------------------------------------

Dear Codalab Team,

We are the organizers of the MEIJU 2025 Challenge, and our competition page can be found at the following link:
Track 1 - English: https://codalab.lisn.upsaclay.fr/competitions/20426;
Track 1 - Mandarin: https://codalab.lisn.upsaclay.fr/competitions/20425;
Track 2 - English: https://codalab.lisn.upsaclay.fr/competitions/20424;
Track 2 - Mandarin: https://codalab.lisn.upsaclay.fr/competitions/20423.

During the course of the competition, we discovered that participants using Windows systems are unable to submit their test results correctly when using Chrome or Edge browsers. The expected submission process is as follows:

1. Click "Submit".
2. A file selection dialog pops up.
3. The participant selects a file.
4. Confirm submission.
5. A success message is displayed, and the results are shown.
6. 
However, these participants encountered an issue at step 4: after confirming submission, no feedback was provided—neither a success message nor an error message. At this point, the "Submit" button becomes grayed out and unclickable.

In contrast, participants using a Mac with Safari or users submitting from mobile devices are able to complete the submission process successfully, and their results are correctly displayed.

We would like to inquire about the possible cause of this issue and how we can resolve it.

Thank you for your attention,
Zuo Haolin
MEIJU 2025 Organizer

If you are having trouble using the site:
-----------------------------------------

1. What browser and version are you using?
A: Chrome (Windows), 130.0.6723.59.

**Comment by Didayolo** [comment] 2024-10-22 14:09
Indeed, submissions are currently not working on Chrome. We are working to upgrade the software and resolve this issue soon.

I close this issue because it is a duplicate of #3503.

**Closed as completed by Didayolo** 2024-10-22 14:09 UTC
